name: KSQL DB Query

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Confluent Cloud CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo curl -L --http1.1 https://cnfl.io/ccloud-cli | sh -s -- -b /usr/local/bin
        ls

    - name: Login to Confluent Cloud
      run: ccloud login --apikey ${{ secrets.CONFLUENT_CLOUD_API_KEY }} --apisecret ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}

    - name: Login to KSQL DB
      run: ccloud ksql-cluster endpoint --cluster-id my_cluster_id | xargs ccloud ksql-cluster ksql-app-auth-add ${{ secrets.CONFLUENT_CLOUD_API_KEY }} ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}

    - name: Run KSQL Query
      run: ccloud ksql http://endpoint:8088 --query "SELECT * FROM my_stream;"
